---

git_repo: git@github.com:paolopaolopaolo/hot-potato-app.git
repo_name: hotpotatoapp

project_name: hotpotatoapp
application_name: hotpotatoapp

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCSTZKoKpd1+noH0b7hYFsc1QUFzgKoQTXsPbR0gFylX9B5xpaUZCISX81iIkHub9MYASTnakxMmRs1K+8HJbPlIz+cYBe+pfYwIohanLb4QOcLBejoeLVxtc6DxTr3F0/Krz5UH1xaVwNos3ymRFaoT7K0zVQE8XBhE0Zvep+pMWSsX2Q+zYXsDu05n/nuYYcLEKsN8y3A/NiXOV9+XuARFBHi+FMeHSTgk2o5mI2xSlC3e5Wsbyai1o9TZFKDmIZMqv0SLxSsw7j4vJpsFoayxxtkX1CVX5+Z+JlGamHRqeLIvM2nNwGnvBS3ra5f3Qh5clJlmAMV5iB6r4BucNEVsvc6C20vq129+GMFaPlE35RTgLps0jWw/LuIOJ9L+Z7EngogNwuKRaZba/tIH79nDvGdZ1ioo7Fm1p5eTyXxFNflHjXbZjLmc3Wok/0kBcQK/L7oUnzx8XK2viw2O/2fb/WX1nXg+guVKkSP3EGproXikVSy0icuo1eAXYfgK/7RbX4tnPE8oAXWoq36aXhmmCTNyVfn4tmDX4yKcWKVMb822Zs000RnBV797KRAcSHltwSegTxptLFUveKlMN3/cx6ac3LA3ljZrYc9T8Ry4fvZQUG/ZJpH/abhDFBhScDJxi0V0vWtLN3J3ChlbIZyEgLCbY2A8altklHQ9ZhMzw==
git_ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEAkk2SqCqXdfp6B9G+4WBbHNUFBc4CqEE17D20dIBcpV/QecaW
  lGQiEl/NYiJB7m/TGAEk52pMTJkbNSvvByWz5SM/nGAXvqX2MCKIWpy2+EDnCwXo
  6Hi1cbXOg8U69xdPyq8+VB9cWlcDaLN8pkRWqE+ytM1UBPFwYRNGb3qfqTFkrF9k
  Ps2F7A7tOZ/57mGHCxCrDfMtwPzYlzlffl7gERQR4vhTHh0k4JNqOZiNsUpQt3uV
  rG8motaPU2RSg5iGTKr9Ei8UrMO4+LyabBaGsscbZF9QlV+fmfiZRmph0aniyLzN
  pzcBp7wUt62uX90IeXJSZZgDFeYgeq+AbnDRFbL3OgttL6tdvfhjBWj5RN+UU4C6
  bNI1sPy7iDifS/mexJ4KIDcLikWmW2v7SB+/Zw7xnWdYqKOxZtaeXk8l8RTX5R41
  22Yy5nN1qJP9JAXECvy+6FJ88fFytr4sNjv9n2/1l9Z14PoLlSpEj9xBqa6F4pFU
  stInLqNXgF2H4Cv+0W1+LZzxPKAF1qKt+ml4ZpgkzclX5+LZg1+MinFilTG/Ntmb
  NNNEZwVe/eykQHEh5bcEnoE8abSxVL3ipTDd/3MemnNywN5Y2a2HPU/EcuH72UFB
  v2SaR/2m4QxQYUnAycYtFdL1rSzdydwoZWyGchICwm2NgPGpbZJR0PWYTM8CAwEA
  AQKCAgBh2yb7+jkCfX2/2yf8YVGv8D+CyW93kN57XC5mOjE9n9+2hADV0kAD4DZk
  rBtDW2JrTOCdNLlCBqpvHyqqsiooWjJC6vcW2rTXL1HaobW0SN0Av3wwegSKwRsX
  ggVVni8Nl7dt1ugTuN2b22nFYDJCM8SJMElBYShUlernx7IhHduDe+52H0uzP6ym
  fX1TV8JWwVhYZU42JijMxWA9C0J9ydnI4WXe34l5+L/1NDeZ3OYuQ6gyBMpn4nFN
  Su3x/UPe5gONdRY0FFmVbbkwEMUZsRl+Qk6JCsOa3e/PbHpvHV2F/NrlPGKMCb4l
  uTLIBfSUHsZEE7AEpr8UsGyL8kO2Z/CU7LUgPUU2VVY19f44Uhxvmxrggu6e2xXk
  VQ6U8XAgNbKnFl7ibw4PnRMeyeIbknB52A10Eb++wUOCrH649HsTz2eH5/KXphwB
  2pPIzq+CsnBuo3QC/ubx7Bn+qQg+13hmwZFLgv/fGsm/OImPDVusMJYa4PoWw5eh
  iyLN57d3h4R5n/mJggRVPk3vaU22Wy+yhTB6xM1Uhb4aUL8AuYByrXCFd2PqwV9k
  SNkwJqg5+Ci6p0EnJy891BiQYBkEbQSLAOz9hSAUAg9oFI2Wu2jC69ODU5lq9ayi
  fP9Gj5DZeHPNRahX6kTszneuRM0cgP+Has2zCGTIWrMkG+CFqQKCAQEAwRHAs0Y0
  SfgRZthYKwisc0+dWzeiAh/S0ul8zovBRIp9/QFYuJBebc8BJvBZaVcRooWbsjPZ
  +cBJcJxGey5eL0iSnKOUT8psUL/MCR7QXoraPm8jFswyeb9kmlTMRQGgcTeKGajC
  k0ToB8FFIyKM9q7RmTBswSMyOPGLU7Q1anWgdTkGX8Jh4tdUhq454Rtxm3ywIO3A
  Q1+3jg4US2BKjtnzyWfOJlMY3Umpvx57c7jsiKxUk22MPP/sOnByHohkwt3c4jS/
  ritQ4IKdLTX2TxWIaVFatflzXHd+ThIaTy55BHIwSfjqSskioAxcU9jMkYMhIOUG
  TfHGWL0uKL7CjQKCAQEAwf2BuSHjxEXgjcEQTNw0shyCkdF42TB4e8CiA0qYpcKg
  tR5/8nQilkKSlzVYDNFpYDo/XTU6l9yu6+zwz3TLUokc0kAJLI0A2bqZF4joUMtO
  mSODi2pZVLUA+uinvbMVWMQOUlqQqTRsKnfJcIfVRWNFk0Ok1r5QuZNnZnXOEuLV
  yefbbR+RcVZjfe+okcVQvbZEoSBRoQdVodXULLekEAK5YM9uXJMyhoQ+46qFaOl+
  DWWa8tBsChz9A1pwdW02b/uj+S8cHbs8wx3gkaANSoPKq4dM1KGTKWnJHDkm+d/K
  LpZtSn0xaLCNxo05RLdVWh4KNW/xMs/qFdAkQ1XjywKCAQBwZm9zb2m9rogjAczC
  sPgE4dLQaiENb42DcJ9SeBZ6Ws5iX0hRmur+rscS7lZ/d0sy/OnZ40oBlqqqvrBh
  wmreyDdirfEISuaoVCDrJl9Uyy2nr3gUK6kvK/fbyYZqnjnT7+ucaJ1us20KJsCj
  Zdf/PWOU9ZY7EsyITkc44e8/HV/fHuXRFg96yrXQ+tmDbkDDruGzKfcGwlDQiO3T
  vClr5QOCu8ZOlY4iNmJ2e76Pbpd2Mi3C7sH4OV5D33bww6M1t4iCwQbe1STur9vl
  mEbfX7/c4JoY2zMIICEOPofGlV2q8ved+SYdh996ofeWcN8Xz+mXhv4Wnq1EuE6J
  NhV5AoIBAGJiheY07+VdYzPBlNjGXdtvZjE6QcY1NQXefsyYiq6W9Ramr1Fx4RDA
  FsSlg1CM7JqnL/e/xUW74OM6ui8dFvl3HKztWTnFEYdbgcVT5C8FzYkRX+fXOhMh
  8atPT7OAHfV1CaZu1CtcsPcg5YMzANE+Nc0oY3Od9icIQUrPuIIPlUnfU4QWnJcU
  r0TxxVaY8gglZs0pLP00URPQ9NjxEj4kg4w758b/yII8lAC3PQ4mTY3R2DIJzqGa
  bh/DQIHtr8w/nbwFToctrPVwM7Lnr5X5HVK9PhQhFhfM1PiBa+kSvOG/3RIISITF
  9kGa4k6dhKY90gOkEHoqxJfnhly4NN0CggEBAIFtHtZ7Zpm0M49BPp8kIfibHvaX
  NpVIrhe1zeRADOFhEmdpQTDx+7dBLaNfH38eN0TRYmntTqtAtPDw9GzCNiMQ/vav
  LwMU0ny04mKMRlX6owB8yCypgagxRvmBHDYzBkPqR5/T4B+EZe7KOmsEJgzZprdo
  aH/a8sJ9513IAMB/AVTtgxahS9jXZ4TZRXIduqc4GuWt5ubBIrWLN1y+EZADU9zE
  L0Tvd4OU56zbN1T2/JXnPJOGbc327zUJD9oIKvG4aG0JqADu9pwbqoBF3HVhXWJt
  Xz8g7RxhGhQt4NkW3Sr02tOberQTy4ADQS7sVaSyXP0bwJyN5Eiz4jKQpc4=
  -----END RSA PRIVATE KEY-----

